@startuml

participant Camera
participant Computer
participant Kafka
participant Spark
participant SQLite
participant Webserver

Camera --> Computer : video/image stream
Computer --> Kafka : information about license plate \n+ timestamp
Kafka --> Spark : license plate event
Spark --> SQLite : Persist state
SQLite <-- Webserver : get information about parking lots
actor User
Webserver <-- User : get information
@enduml

' encrypt/encode licence plate to a unique ID for security