@startuml

box Sensor
participant Camera
end box
box Device
participant Computer
end box
box Cloud
participant MQTTBroker
end box
box Device
participant Spark
participant Kafka
participant Webserver
end box

Camera --> Computer : video/image stream
Computer --> MQTTBroker : information about license plate \n+ timestamp
MQTTBroker --> Spark : MQTT message
Spark --> Kafka : license plate event
Kafka <-- Webserver : get information about license plate \n+ timestamp
actor User
Webserver <-- User : get information
@enduml

' encrypt/encode licence plate to a unique ID for security