@startuml

(check the fulfillment of the parking lot) as (fulfillment)

User --> (check the parking lot of his motorbike)
User --> (fulfillment)
User -> (check the current load of the gate)

note right of (fulfillment)
based on the frequency of bikes
entering/leaving the gate in the
near past (~2mins)
end note

@enduml